name = "authnone"
main = "./src/index.ts"
compatibility_date = "2022-05-03"
site = { bucket = "./fdist" }

[durable_objects]
bindings = [
  {name = "SESSION", class_name = "Session"},
  {name = "WEBSITE", class_name = "Website"}
]

[[migrations]]
tag = "v1"
new_classes = ["Session", "Website"]