name = "mamamura-auth"
main = "./src/index.ts"
compatibility_date = "2022-05-03"
site = { bucket = "./fdist" }

kv_namespaces = [
  { binding = "USERS", id = "f6f81ed4b4f3403abcbf428cf7620d4e" }
]

[vars]
APP_HOST = "https://auth.mamamura.jp"
ENV = "production"

[observability.logs]
enabled = true

[durable_objects]
bindings = [
  {name = "USER", class_name = "User"},
  {name = "SESSION", class_name = "Session"},
]

[[migrations]]
tag = "v1"
new_classes = ["User", "Session"]
