name = "authnone"
main = "./src/index.ts"
compatibility_date = "2022-05-03"
site = { bucket = "./fdist" }

kv_namespaces = [
  { binding = "USERS", id = "3f6b7bb519a843df8f5e201b2d19b6d5", preview_id = "345ab6fe79e74ab5803fd39a24f9435f" }
]

[vars]
APP_HOST = "https://authn.one"
ENV = "production"

[durable_objects]
bindings = [
  {name = "USER", class_name = "User"},
  {name = "SESSION", class_name = "Session"},
]

[[migrations]]
tag = "v1"
new_classes = ["User", "Session"]